[package]
name = "tbx"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
members = [
    "tbx-essential",
    "tbx-foundation",
    "tbx-operation",
    "tbx-toolbox",
]

[dependencies]
