[package]
name = "tbx_model"
version = "0.2.0"
edition = "2021"
description = "Domain model definition and implementation"

[dependencies]
tbx_essential = { path = "../tbx_essential" }
pest = "2"
pest_derive = "2"