[package]
name = "tbx_essential"
version = "0.2.2"
edition = "2021"
description = "essential library modules. Most module/functions are wrappers of external libraries."

[dependencies]
rand = "0.8"
regex = "1"
